import type { Category } from '~/pages/category/columns';

export const dataFake: Category[] = [
  { id: '1', name: 'Laptop', description: 'Máy tính xách tay', status: true },
  { id: '2', name: 'Máy tính bàn', maintenanceIntervalHours: 4320, status: true },
  { id: '3', name: 'Máy in', status: false },
  { id: '4', name: 'Camera', status: true },
  { id: '5', name: 'Chuột', status: true },
  { id: '6', name: 'Bàn phím', status: true },
  { id: '7', name: 'Màn hình', status: true },
  { id: '8', name: 'RAM', status: true },
  { id: '9', name: 'SSD', status: true },
  { id: '10', name: 'HDD', status: true },

  { id: '11', name: 'Switch mạng', status: true },
  { id: '12', name: 'Router', status: true },
  { id: '13', name: 'Hub USB', status: true },
  { id: '14', name: 'Máy chiếu', status: true },
  { id: '15', name: 'UPS', status: false },
  { id: '16', name: 'Tivi', status: true },
  { id: '17', name: 'Ổ cắm thông minh', status: true },
  { id: '18', name: 'Loa bluetooth', status: true },
  { id: '19', name: 'Máy quét barcode', status: true },
  { id: '20', name: 'Micro', status: true },

  { id: '21', name: 'Máy fax', status: false },
  { id: '22', name: 'Modem 4G', status: true },
  { id: '23', name: 'NAS Server', status: true },
  { id: '24', name: 'Backup Drive', status: true },
  { id: '25', name: 'Máy cắt nhãn', status: true },
  { id: '26', name: 'Máy scan', status: true },
  { id: '27', name: 'Máy hủy giấy', status: true },
  { id: '28', name: 'Bộ lưu điện mini', status: true },
  { id: '29', name: 'Thiết bị chống sét lan truyền', status: true },
  { id: '30', name: 'Máy rung cảnh báo', status: true },

  { id: '31', name: 'Card mạng', status: true },
  { id: '32', name: 'Card đồ họa', status: true },
  { id: '33', name: 'CPU', status: true },
  { id: '34', name: 'Nguồn máy tính', status: true },
  { id: '35', name: 'Tản nhiệt nước', status: true },
  { id: '36', name: 'Tản nhiệt khí', status: true },
  { id: '37', name: 'Webcam', status: true },
  { id: '38', name: 'Bộ chia HDMI', status: true },
  { id: '39', name: 'Bàn nâng hạ', status: true },
  { id: '40', name: 'Ghế xoay', status: true },

  { id: '41', name: 'Đầu đọc thẻ', status: true },
  { id: '42', name: 'Đầu đọc RFID', status: true },
  { id: '43', name: 'Tablet', status: true },
  { id: '44', name: 'Chromebook', status: true },
  { id: '45', name: 'Surface', status: false },
  { id: '46', name: 'Thin Client', status: true },
  { id: '47', name: 'Máy POS', status: true },
  { id: '48', name: 'Access Point', status: true },
  { id: '49', name: 'Firewall thiết bị', status: true },
  { id: '50', name: 'Thiết bị load balancer', status: true },

  { id: '51', name: 'Ổ cứng gắn ngoài', status: true },
  { id: '52', name: 'Ổ đĩa quang', status: false },
  { id: '53', name: 'Docking Station', status: true },
  { id: '54', name: 'Máy đọc tài liệu', status: true },
  { id: '55', name: 'Đèn bàn thông minh', status: true },
  { id: '56', name: 'Bộ điều khiển trung tâm', status: true },
  { id: '57', name: 'Cảm biến nhiệt', status: true },
  { id: '58', name: 'Cảm biến độ ẩm', status: true },
  { id: '59', name: 'Cảm biến chuyển động', status: true },
  { id: '60', name: 'Thiết bị cảnh báo cháy', status: true },

  { id: '61', name: 'Ổ khóa vân tay', status: true },
  { id: '62', name: 'Camera IP', status: true },
  { id: '63', name: 'Bộ phát wifi mesh', status: true },
  { id: '64', name: 'Dây mạng Cat6', status: true },
  { id: '65', name: 'Dây nguồn 2 chấu', status: true },
  { id: '66', name: 'Ổ cắm ICT', status: true },
  { id: '67', name: 'Ổ cứng enterprise', status: true },
  { id: '68', name: 'Máy đo điện', status: true },
  { id: '69', name: 'Máy đo nhiệt', status: true },
  { id: '70', name: 'Máy đo độ ồn', status: true },

  { id: '71', name: 'Máy điều hòa mini', status: true },
  { id: '72', name: 'Quạt hút', status: true },
  { id: '73', name: 'Bộ chia USB-C', status: true },
  { id: '74', name: 'Máy phun sương', status: true },
  { id: '75', name: 'Loa họp trực tuyến', status: true },
  { id: '76', name: 'Micro hội nghị', status: true },
  { id: '77', name: 'AirTag', status: true },
  { id: '78', name: 'Máy kiểm kho', status: true },
  { id: '79', name: 'Barcode Printer', status: true },
  { id: '80', name: 'NAS Backup', status: true },

  { id: '81', name: 'Laptop Gaming', status: true },
  { id: '82', name: 'Laptop Ultrabook', status: true },
  { id: '83', name: 'Laptop Workstation', status: true },
  { id: '84', name: 'Máy quét 3D', status: true },
  { id: '85', name: 'Máy in 3D', status: false },
  { id: '86', name: 'Máy đọc mã QR', status: true },
  { id: '87', name: 'Card âm thanh', status: true },
  { id: '88', name: 'Máy chiếu siêu gần', status: true },
  { id: '89', name: 'Camera giám sát 360', status: true },
  { id: '90', name: 'Đầu ghi hình NVR', status: true },

  { id: '91', name: 'Ổ cứng Fibre Channel', status: true },
  { id: '92', name: 'Module SFP+', status: true },
  { id: '93', name: 'Máy chủ mini', status: true },
  { id: '94', name: 'Máy chủ rack 1U', status: true },
  { id: '95', name: 'Máy chủ rack 2U', status: true },
  { id: '96', name: 'Máy chủ tower', status: true },
  { id: '97', name: 'Mainboard', status: true },
  { id: '98', name: 'Power Module', status: true },
  { id: '99', name: 'Bộ nguồn dự phòng', status: true },
  { id: '100', name: 'Thiết bị cân chỉnh laser', status: true },
];
